#!/bin/bash
set -e

VERSION="0.1.0"

function make_snapshot() {
  containername="$1"
  snapshotname="$2"
  # First make a snapshot of the current state
  # Save it as a new image with the current date appended, so we don't overwrite another image
  podman container commit -p "$containername" "$snapshotname-$(date -u +%Y-%m-%dt%H-%M-%S)"
}

function prune_snapshots() {
  containername="$1"
  snapshotname="$2"
  num_of_snapshots="$3"

  # Get current image
  current_image=$(current_container_image "$containername")

  # Prune the snapshots
  # 1. podman sorts images according to creation date. 
  # 2. Filter out the currently used image.
  # 3. tail-syntax needs us to add one to the number of lines we want to skip
  # 4. and xargs will remove all remaining images
  tail_num=$((num_of_snapshots+1))
  podman images --no-trunc --format "{{.Id}}" --filter "reference=$snapshotname-*" | grep -v "$current_image" | tail -n +$tail_num | xargs -r podman rmi
}

function update_container() {
  containername="$1"
  snapshotname="$2"
  num_of_snapshots="$3"

  make_snapshot "$containername" "$snapshotname"

  # Then run the updates on it
  distrobox upgrade "$containername"

  prune_snapshots "$containername" "$snapshotname" "$num_of_snapshots"
}

function list_snapshots() {
  snapshotname="$1"
  podman images --no-trunc --format "{{.Repository}}" --filter "reference=$snapshotname-*" 
}

function current_container_image() {
  containername="$1"
  podman container ls -a --no-trunc --format "{{.ImageID}}" --filter "name=$containername"
}

function rollback_to_image() {
  containername="$1"
  rollback_image="$2"

  # Get current image
  current_image=$(current_container_image "$containername")

  podman container stop "$containername"
  podman container rm "$containername"

  distrobox create -i "$rollback_image" -n "$containername"

  # Remove no longer used current image
  podman rmi "$current_image"
}

function run_current() {
  if [ $# -ne 2 ]; then
    print_current_usage_and_exit
  fi
  
  containername="$2"
  podman container ls -a --no-trunc --format "{{.Image}}" --filter "name=$containername"
}

function run_list() {
  if [ $# -ne 2 ]; then
    print_list_usage_and_exit
  fi
  
  snapshotname="$2"
  list_snapshots "$snapshotname" 
}

function run_create() {
  if [ $# -ne 3 ]; then
    print_create_usage_and_exit
  fi
  
  containername="$2"
  snapshotname="$3"
  make_snapshot "$containername" "$snapshotname" 
}

function run_remove() {
  if [ $# -ne 2 ]; then
    print_remove_usage_and_exit
  fi
  
  snapshotname="$2"
  podman rmi "$snapshotname" 
}

function run_prune() {
  if [ $# -ne 4 ]; then
    print_prune_usage_and_exit
  fi
  
  containername="$2"
  snapshotname="$3"
  num_of_snapshots="$4"
  prune_snapshots "$containername" "$snapshotname" "$num_of_snapshots"
}

function run_rollback() {
  if [ $# -ne 3 ]; then
    print_rollback_usage_and_exit
  fi
  
  containername="$2"
  rollback_image="$3"
  rollback_to_image "$containername" "$rollback_image" 
}

function run_update() {
  if [ $# -ne 4 ]; then
    print_update_usage_and_exit
  fi
  
  containername="$2"
  snapshotname="$3"
  num_of_snapshots="$4"
  update_container "$containername" "$snapshotname" "$num_of_snapshots"
}

function main() {
  # Exit script on CTRL+C
  trap "exit" INT

  if [ $# -le 0 ]; then
    print_main_usage_and_exit
  fi
  
  case "$1" in
      current)
        run_current "$@"
        shift
        ;;
      list|ls)
        run_list "$@"
        shift
        ;;
      create)
        run_create "$@"
        shift
        ;;
      remove|rm)
        run_remove "$@"
        shift
        ;;
      prune)
        run_prune "$@"
        shift
        ;;
      rollback)
        run_rollback "$@"
        shift
        ;;
      update)
        run_update "$@"
        shift
        ;;
      *)
        print_main_usage_and_exit
        ;;
    esac
}

function print_current_usage_and_exit() {
  echo "Usage: distro-snapper current DISTROBOX_NAME"
  echo ""
  echo "Options:"
  echo "    DISTROBOX_NAME: Which snapshot is this container running on"
  exit 1
}

function print_list_usage_and_exit() {
  echo "Usage: distro-snapper list SNAPSHOT_PREFIX"
  echo ""
  echo "Options:"
  echo "    SNAPSHOT_PREFIX: Which snapshots should be listed"
  exit 1
}

function print_remove_usage_and_exit() {
  echo "Usage: distro-snapper remove SNAPSHOT_PREFIX"
  echo ""
  echo "Options:"
  echo "    SNAPSHOT_PREFIX: Which snapshots should be removed"
  exit 1
}

function print_create_usage_and_exit() {
  echo "Usage: distro-snapper create DISTROBOX_NAME SNAPSHOT_PREFIX"
  echo ""
  echo "Options:"
  echo "    DISTROBOX_NAME: Which container to snapshot"
  echo "    SNAPSHOT_PREFIX: How the snapshot-prefix should be named (snapshot-date will be appended)"
  exit 1
}

function print_prune_usage_and_exit() {
  echo "Usage: distro-snapper prune DISTROBOX_NAME SNAPSHOT_PREFIX NUM_OF_SNAPSHOTS"
  echo ""
  echo "Options:"
  echo "    DISTROBOX_NAME: Which container is affected"
  echo "    SNAPSHOT_PREFIX: Which associated snapshot-prefix"
  echo "    NUM_OF_SNAPSHOTS: How many snapshots should remain"
  exit 1
}

function print_rollback_usage_and_exit() {
  echo "Usage: distro-snapper rollback DISTROBOX_NAME TARGET_SNAPSHOT"
  echo ""
  echo "Options:"
  echo "    DISTROBOX_NAME: Which container to restore"
  echo "    TARGET_SNAPSHOT: To which snapshot to restore"
  exit 1
}

function print_update_usage_and_exit() {
  echo "Usage: distro-snapper update DISTROBOX_NAME SNAPSHOT_PREFIX NUM_OF_SNAPSHOTS"
  echo ""
  echo "Convenience function, which creates a snapshot, runs \`distrobox update\` and then prunes the remaining snapshots"
  echo "Options:"
  echo "    DISTROBOX_NAME: Which container to update"
  echo "    SNAPSHOT_PREFIX: Which associated snapshot-prefix"
  echo "    NUM_OF_SNAPSHOTS: How many snapshots should remain"
  exit 1
}

function print_main_usage_and_exit() {
  echo "distro-snapper version: $VERSION"
  echo ""
  echo "Choose one of the following commands:"
  echo "    current"
  echo "    list | ls"
  echo "    create"
  echo "    remove | rm"
  echo "    prune"
  echo "    rollback"
  echo "    update"
  echo "    help"
  exit 1
}

main "$@"
